enum RequestType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  GET_RATE_LIST = 'GET_RATE_LIST',
    GET_BRANCHES_NAME = 'GET_BRANCHES_NAME',
     GET_DEAL_LIST=' GET_DEAL_LIST',
     GET_BRANCHES_NAME_LIST='GET_BRANCHES_NAME_LIST',
     GET_PURPOSE_LIST='GET_PURPOSE_LIST'
}

export default RequestType;