enum RequestType {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  GET_RATE_LIST = 'GET_RATE_LIST',
    GET_BRANCHES_NAME = 'GET_BRANCHES_NAME',
     GET_DEAL_LIST=' GET_DEAL_LIST',
     GET_BRANCHES_NAME_LIST='GET_BRANCHES_NAME_LIST',
     GET_PURPOSE_LIST='GET_PURPOSE_LIST',
     GET_COUNTRY_LIST='GET_COUNTRY_LIST',
     GET_PROVINCE_LIST='GET_PROVINCE_LIST',
     GET_OCCUPATION_LIST='GET_OCCUPATION_LIST',
     UPDATE_IMAGE='UPDATE_IMAGE'
}

export default RequestType;